version: 2

before:
  hooks:
    - go mod tidy
    - go test ./... -count=1

builds:
  - id: koor-server
    main: ./cmd/koor-server
    binary: koor-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

  - id: koor-cli
    main: ./cmd/koor-cli
    binary: koor-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

  - id: koor-wizard
    main: ./cmd/koor-wizard
    binary: koor-wizard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  prerelease: auto
  header: |
    ## Koor {{ .Version }}

    Coordination server for AI coding agents.

    ### Installation

    Download the archive for your platform, extract, and place the binaries on your PATH.

    ```bash
    ./koor-wizard    # Scaffold a project
    ./koor-server    # Start the server
    ./koor-cli status
    ```
